# Generated by Django 5.1.7 on 2025-03-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Contacts'},
        ),
    ]
