# Generated by Django 5.1.7 on 2025-03-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('classmate', 'Classmate'), ('neighbor', 'Neighbor'), ('acquaintance', 'Acquaintance')], max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contact',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.relation'),
        ),
    ]
